name: 'Pulumi Helm Updater'
description: 'Determine if a update to a pulumi managed helm chart is available'
author: 'LambArchie'
inputs:
  stack_name: # change this
    required: true
    description: 'Pulumi Stack to Check'
runs:
  using: 'node16'
  main: 'dist/index.js'
