name: CI

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 14, 16, 18 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Up Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Install
        shell: bash
        run: |-
          npm ci

      - name: Build
        shell: bash
        run: |-
          npm run build

      - name: Lint
        shell: bash
        run: |-
          npm run lint

      - name: Test
        shell: bash
        run: |-
          npm run test

      - name: Package
        shell: bash
        run: |-
          npm run package
